# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='input_ulasan',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
