# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0002_auto_20170326_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulasan', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='result',
            old_name='buku',
            new_name='judul',
        ),
        migrations.RemoveField(
            model_name='book',
            name='input_ulasan',
        ),
        migrations.AddField(
            model_name='review',
            name='judul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifyme.Book'),
        ),
    ]
