# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0003_auto_20170326_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klasifikasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulasan', models.FileField(blank=True, null=True, upload_to='')),
                ('hasil_klasifikasi', models.CharField(max_length=7)),
            ],
        ),
        migrations.RenameModel(
            old_name='Book',
            new_name='Buku',
        ),
        migrations.RemoveField(
            model_name='result',
            name='judul',
        ),
        migrations.RemoveField(
            model_name='review',
            name='judul',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='klasifikasi',
            name='judul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifyme.Buku'),
        ),
    ]
