# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0004_auto_20170326_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klasifikasi',
            name='ulasan',
        ),
        migrations.AddField(
            model_name='buku',
            name='ulasan',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
