# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0005_auto_20170326_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='ulasan',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
