# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0006_auto_20170329_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='ulasan',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/'),
        ),
    ]
