# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0007_auto_20170403_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pengguna', models.CharField(max_length=10)),
                ('kata_sandi', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=30)),
                ('nama_depan', models.CharField(max_length=10)),
                ('nama_belakang', models.CharField(max_length=10)),
                ('foto', models.ImageField(blank=True, upload_to='picture/')),
            ],
        ),
    ]
