# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0008_akun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buku',
            old_name='ulasan',
            new_name='ulasan_negatif',
        ),
        migrations.AddField(
            model_name='buku',
            name='ulasan_positif',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='akun',
            name='nama_pengguna',
            field=models.CharField(max_length=20),
        ),
    ]
