# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0010_buku_ulasan_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='priors_neg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buku',
            name='priors_pos',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
