# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0011_auto_20170411_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='hasil_neg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buku',
            name='hasil_pos',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
