# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0012_auto_20170411_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='hasil_klasifikasi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
