# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0013_buku_hasil_klasifikasi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buku',
            old_name='ulasan_testing',
            new_name='testing_set',
        ),
        migrations.RenameField(
            model_name='buku',
            old_name='ulasan_negatif',
            new_name='training_set_negatif',
        ),
        migrations.RenameField(
            model_name='buku',
            old_name='ulasan_positif',
            new_name='training_set_positif',
        ),
    ]
