# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0015_auto_20170417_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSetNeg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_set_negatif', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSetPos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_set_positif', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='buku',
            name='training_set_negatif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classifyme.TrainingSetNeg'),
        ),
        migrations.AlterField(
            model_name='buku',
            name='training_set_positif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classifyme.TrainingSetPos'),
        ),
    ]
