# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0017_auto_20170417_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingsetneg',
            old_name='training_set_negatif',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='trainingsetpos',
            old_name='training_set_positif',
            new_name='file',
        ),
    ]
