# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0018_auto_20170417_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='hasil_preprocessing_neg',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='buku',
            name='hasil_preprocessing_pos',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsetneg',
            name='nama',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsetpos',
            name='nama',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
