# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0019_auto_20170420_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hasil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('total_pos', models.IntegerField(blank=True, null=True)),
                ('total_neg', models.IntegerField(blank=True, null=True)),
                ('hasil_klasifikasi', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='buku',
            name='hasil_klasifikasi',
        ),
    ]
