# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0022_auto_20170430_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resensi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testing_set', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/')),
            ],
        ),
        migrations.RemoveField(
            model_name='buku',
            name='hasil_preprocessing_neg',
        ),
        migrations.RemoveField(
            model_name='buku',
            name='hasil_preprocessing_pos',
        ),
        migrations.AddField(
            model_name='buku',
            name='jumlah_neg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buku',
            name='jumlah_pos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resensi',
            name='judul',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classifyme.Buku'),
        ),
        migrations.AddField(
            model_name='resensi',
            name='training_set_negatif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classifyme.TrainingSetNeg'),
        ),
        migrations.AddField(
            model_name='resensi',
            name='training_set_positif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classifyme.TrainingSetPos'),
        ),
    ]
