# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0024_resensi_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='nama',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
