# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0026_remove_buku_nama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resensi',
            name='judul',
        ),
        migrations.RemoveField(
            model_name='resensi',
            name='training_set_negatif',
        ),
        migrations.RemoveField(
            model_name='resensi',
            name='training_set_positif',
        ),
        migrations.DeleteModel(
            name='Resensi',
        ),
    ]
