# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0027_auto_20170501_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='jumlah_neg',
        ),
        migrations.RemoveField(
            model_name='buku',
            name='jumlah_pos',
        ),
    ]
