# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 12:36
from __future__ import unicode_literals

import classifyme.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0029_auto_20170523_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsetneg',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/', validators=[classifyme.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='trainingsetpos',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/', validators=[classifyme.validators.validate_file_extension]),
        ),
    ]
