# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0032_auto_20170523_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='tahun_terbit',
            field=models.IntegerField(choices=[(2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2017),
        ),
    ]
